### ISSUE TITLE
enable disable autofix

### ISSUE THREAD

**Issue by sibelius** [edvardchen/eslint-plugin-i18next#1]
it is adding i18next.t even when I have already t('myKey')

**Comment by edvardchen** [comment]
A quick workaround is to add `t` into ‘ignoreCallee` option. 

Maybe we need another option to specify the translation function name used by auto-fix. It is replaced with `i18next.t` right now.

`t` is a trivial name. Allowing to call `t` is not a good idea, IMO.

**Comment by osdiab** [comment]
though given that I use `react-i18next` and get the `t` function using React Hooks as opposed to getting it off the `i18next` object, that suggested flow isn't great. that blunt `ignoreCallee` option is what i'll probably be going with if we go with this eslint plugin on my project.

**Comment by edvardchen** [comment]
> A quick workaround is to add `t` into ‘ignoreCallee` option.
> 
> Maybe we need another option to specify the translation function name used by auto-fix. It is replaced with `i18next.t` right now.
> 
> `t` is a trivial name. Allowing to call `t` is not a good idea, IMO.

closed
