### ISSUE TITLE
Another way to ignore attributes of DOM

### ISSUE THREAD

**Issue by edvardchen** [edvardchen/eslint-plugin-i18next#10]
For native DOM elements, instead of appending more ”allowed“ attributes, should we ignore all attributes but just check some attributes like "placeholder" ? 

There are very few attributes of native DOM elements that can be displayed to user.

**Comment by edvardchen** [comment]
@fibo @7ixi0

**Comment by fibo** [comment]
@edvardchen it could be a better approach to whitelist instead of blacklist, can you give some hint where or how it could be implemented in the code, optionally creating a new branch with this purpouse?

**Comment by edvardchen** [comment]
For native DOM tags like `video`, `img`, `input`, most attributes would not be displayed to user. Instead making a long long whitelist, we just check a few case like `value` of `input`, `placeholder`, `alt` etc. Here we use **blacklist**

For user custom JSX tag, we still prefer **whitelist**, that check all attributes except those listed in `whitelist`
