### ISSUE TITLE
`@next` version still pointing at `6.0.0-2`

### ISSUE THREAD

**Issue by tetarchus** [edvardchen/eslint-plugin-i18next#101]
Hi,

It looks like the installation method mentioned in the [README](https://github.com/edvardchen/eslint-plugin-i18next/#installation) is pointing at the incorrect version (`6.0.0-2`).

Running `npm install eslint-plugin-i18next@next --save-dev` tag adds  
> `"eslint-plugin-i18next": "^6.0.0-2"` 

to `package.json`, but using without the `@next` tag adds 
> `"eslint-plugin-i18next": "^6.0.0-8"`.

Discovered as was having issues with ternary strings which pointed me to #79 which said it had been fixed in `6.0.0-5` and my version was lower, despite only just having installed the package.

**Comment by edvardchen** [comment]
It's misguiding. I will correct readme next week.
