### ISSUE TITLE
Notice and skip emojis and HTML entities

### ISSUE THREAD

**Issue by igorsantos07** [edvardchen/eslint-plugin-i18next#105]
First of all, this plugin is life-changing for my team of lazy devs :joy: 

But then, we noticed we every now and then need to use the (verbose) `eslint-disable` comment in places that really don't need to be translated, namely strings composed of emojis or entities/symbols (such as the infamous `&times;` for popup closure).

It would be great if the plugin was able to identify that and skip notifying.

**Comment by edvardchen** [comment]
kinda similar to https://github.com/edvardchen/eslint-plugin-i18next/issues/93.

I think it might be feasible to ignore [emoji](https://stackoverflow.com/questions/18862256/how-to-detect-emoji-using-javascript) and html entities

The basic idea is to find a list of appropriate regex which represent these special characters and add them into the default configuration [words.exclude ](https://github.com/edvardchen/eslint-plugin-i18next/blob/main/lib/options/defaults.json). 

It takes time to try it out
