### ISSUE TITLE
Ability to ignore full page?

### ISSUE THREAD

**Issue by ChloeSheasby** [edvardchen/eslint-plugin-i18next#121]
Hello, is there a way to ignore a full page? For example, I do not want to add localization to my NotFound page, but it seems strange to have to ignore all of the words. 

I also tried to exclude custom components I've made under the `jsx-components` attribute in the rules, but I don't think that custom components are included in those rules.

**Comment by edvardchen** [comment]
Static analysis cannot predict which code is used in your NotFound page. It's determined at runtime.

Instead, you can use [overrides](https://eslint.org/docs/v8.x/use/configure/configuration-files#how-do-overrides-work) to turn off the rule for specific files
