### ISSUE TITLE
eslint-plugin-i18next does not work with ESLint v9

### ISSUE THREAD

**Issue by vpishuk** [edvardchen/eslint-plugin-i18next#129]
Thie plugin stopped working with ESLint v9.

**Comment by edvardchen** [comment]
Could you share you eslitn config and this plugin version?

**Comment by vpishuk** [comment]
Here is my eslint config:
https://github.com/laverve/utilities/blob/main/packages/eslint-utils/src/eslint.config.js
Plugins version that I tried is the latest one.
E2lint v9 is using flat format as a default one.

**Comment by edvardchen** [comment]
The config didn't use `eslint-plugin-iq8next` at all. Did you provide the wrong branch of the repo?

**Comment by vpishuk** [comment]
It's not there because I haven't figured out how to get flat config from this plugin which is required by eslint v9.

**Comment by vpishuk** [comment]
I have figured out how to add it without flat config thanks to modules provided by eslint for backward compatibility. It would be nice to address this issue on plugin level.

Here is my solution:
```
import eslintJs from "@eslint/js";

import { fixupPluginRules } from "@eslint/compat";
import { FlatCompat } from "@eslint/eslintrc";

import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: eslintJs.configs.recommended
});

function legacyPlugin(name, alias = name) {
    const plugin = compat.plugins(name)[0]?.plugins?.[alias];

    if (!plugin) {
        throw new Error(`Unable to resolve plugin ${name} and/or alias ${alias}`);
    }

    return fixupPluginRules(plugin);
}

export const config = [
    ...compat.extends("plugin:i18next/recommended"),
    {
        plugins: {
            i18next: legacyPlugin("eslint-plugin-i18next", "i18next")
        },
        rules: {}
    }
];

```

**Comment by edvardchen** [comment]
could you try this 

```js
import i18next from 'eslint-plugin-i18next';

export default [
  {
    plugins: { i18next },
    rules: {
      'i18next/no-literal-string': ['error', { mode: 'all' }],
    },
  },
];

```

**Comment by vpishuk** [comment]
@edvardchen thank you! This wirks. It would be nice to add it into the docs. It would be great to export sharable config for eslint9.

**Comment by edvardchen** [comment]
Let me guess. You mean like this?
```js
// eslint.config.js
import jsdoc from 'eslint-plugin-jsdoc';

export default [
  jsdoc.configs['flat/recommended'],
];
```

**Comment by vpishuk** [comment]
Yes, this would be great.
