### ISSUE TITLE
Do you have any plan to support Vue framework?

### ISSUE THREAD

**Issue by fants613** [edvardchen/eslint-plugin-i18next#133]
I tried this plugin,it's a powerful tool, but we have some projects based on Vue,seems this tool can't integrate with Vue properly, it can not recognize these scenarios: 1. string literal in mustaches 2. string literal in Vue component prop value.for example:
```
<template>
  <div>{{ "this is a string literal in mustaches" }}</div>
  <myVueComponent title="this is my title"></myVueComponent>
</template>
```
So, want to know if you have any plan to support these features In the short term.

**Comment by fants613** [comment]
@edvardchen  looking forward to this feature can be implemented as soon as possible, or do you mind I raise a pull request to support it? I think I have time to do this

**Comment by edvardchen** [comment]
sure. Pr is welcome

**Comment by fants613** [comment]
> sure. Pr is welcome

ok, working on it
