### ISSUE TITLE
Allow regex patterns in ignore lists

### ISSUE THREAD

**Issue by ivan-aksamentov** [edvardchen/eslint-plugin-i18next#19]
Add capability to add regex patterns along with strings in ignore lists.

For example, if I want to ignore all functions starting with "foo" (e.g. "foo()", "foo1()", "fooTwo()") and a function "bar()", I would add:

```js
{ ignoreCallee: [/foo.*/, 'bar'] }

```

This would allow non-exhaustive checks, that is, to ignore a list of items where elements are not known in advance (or tedious to enumerate).

Related to https://github.com/edvardchen/eslint-plugin-i18next/issues/18 (the code will probably be shared)

**Comment by edvardchen** [comment]
1. You can't write regex in yaml. So all ignore-options must be strings.
2. Sure, we can use `new RegExp(...)` to transform from string, like I did with `ignore` option. But when user input `i18next.t` then would match `i18nextxt` or `i18nextyt`.  
3. The `dot` character is important in `ignoreCallee` that tell the plugin to do upward lookup.

**Comment by ivan-aksamentov** [comment]
@edvardchen Is there a way to allow regular expressions in `.eslintrc.js` only?

Like this:

{ ignoreCallee: [/foo.*/, 'bar'] }

or like this:

{ ignoreCallee: [RegExp('foo.*'), 'bar'] }

?

**Comment by edvardchen** [comment]
@ivan-aksamentov 
No, I would not support `RegExp` . Neither other eslint plugins did. 

The other option is we can treat string as `RegExp`, like I did to `ignore` option.

```js
{ ignoreCallee: ["foo.*", 'bar'] }
```
Sure, then we can skip function call like `fooA(...)` or `fooB(...)`

But this would violate current behavior. 

For example in `README`

```js
/*eslint i18next/no-literal-string: ["error", { "ignoreCallee": ["yourI18n.method"] }]*/
const bar = yourI18n.method('bar');
```
And users don't expect the plugin to skip `yourI18nXmethod(...)`, do they?

**Comment by ivan-aksamentov** [comment]
@edvardchen Yes, I understand the issues with treating the strings as regexes. Although if you are willing to implement it as it a breaking change (in version  4), then we could declare all strings regexes. So that when transitioning to version 4 users would have to escape their dots and other special characters.

Some popular plugins do treat strings as regexes: https://github.com/benmosher/eslint-plugin-import#importignore

> No, I would not support RegExp . Neither other eslint plugins did.

Given the complications with strings-as-regexes, why not? Eslint and plugins support filename wildcards in some places (which probably requires using some library or a custom parser), so I don't see how regexes are fundamentally different.

See for example eslint's own `override`: https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files

I've no idea how that works, but just want to understand the reasoning here.

**Comment by edvardchen** [comment]
@ivan-aksamentov You misunderstood me. What I said was that I wouldn't support JS type [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp). 

I agree that we can make a breaking change to treat `ignoreCallee` not literal strings but `regular expression in strings`

**Comment by ivan-aksamentov** [comment]
@edvardchen 
> You misunderstood me. What I said was that I wouldn't support JS type RegExp.

This is how I understood it and then asked why :)

**Comment by edvardchen** [comment]
Forget it. Actually this plugin would support it while supporting regexp-in-strings

**Comment by edvardchen** [comment]
@ivan-aksamentov plz see the  following added test case is enough or not
```js
// valid
    {
      code: 'foo.bar("taa");',
      options: [
        {
          ignoreCallee: [/foo.+/]
        }
      ]
    },
```

**Comment by ivan-aksamentov** [comment]
@edvardchen Yes. Thanks so much!
Can't wait for the new release. :)

**Comment by edvardchen** [comment]
try version v4
