### ISSUE TITLE
Error: Failed to load plugin 'i18next' declared in '.eslintrc': Cannot find module 'typescript'

### ISSUE THREAD

**Issue by Velveeta** [edvardchen/eslint-plugin-i18next#27]
The latest release (`4.3.0`) has a reference to `require('typescript') on line 12 of `lib/rules/no-literal-string.js`, but `typescript` isn't listed as a `dependency` or `peerDependency` in the package, so doesn't get added to (or sourced from) the project alongside it during installation. Had to install `4.2.0` instead, because I didn't want to add typescript to my project just for an eslint plugin.

**Comment by edvardchen** [comment]
Sorry. My mistake. I will fix it this weekend

**Comment by Velveeta** [comment]
Thanks! :)
