### ISSUE TITLE
Support ignoring default argument values

### ISSUE THREAD

**Issue by theghostbel** [edvardchen/eslint-plugin-i18next#28]
Didn't find a config option to allow default argument values:
```
function test(value = 'default value') {
  return value;
}
```

The only solution is to use create a UPPER_CASED variable and use it as the default value:
```
const DEFAULT_VALUE = 'default value'
function test(value = DEFAULT_VALUE) {
  return value;
}
```
This works but increases the code. Imagine, how it works if we have several string arguments with default values.

**Comment by edvardchen** [comment]
Reasonable. I try to support it this weekend @theghostbel
