### ISSUE TITLE
How to ignore test files?

### ISSUE THREAD

**Issue by jakubmichalec** [edvardchen/eslint-plugin-i18next#37]
```
test.each`
  firstName     | lastName                 | userName    | expected
  ${"John"} | ${"Doe"} | ${"johhnie"} | ${"John Doe(johhnie)"}
```
I have test file with spec like above (jest), how to ignore gloabally checking it?

**Comment by edvardchen** [comment]
plz see the official document https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories.

**Comment by jakubmichalec** [comment]
yup but then I would disable it globally, when I want other eslint stuff to work it that files :(

**Comment by edvardchen** [comment]
Try [overrides](https://eslint.org/docs/user-guide/configuring#example-configuration) option

**Comment by ismay** [comment]
For people encountering this issue, so what you can do is add a section like this to your eslint config:

```
    overrides: [
        {
            files: ['*.test.js'],
            rules: {
                'i18next/no-literal-string': 'off',
            },
        },
    ],
```

(Or something similar, depending on your setup)
