### ISSUE TITLE
Ignore object property name as a string

### ISSUE THREAD

**Issue by ivansky** [edvardchen/eslint-plugin-i18next#42]
We upgraded to 6 version and the issue appears, is it intended behaviour?
![Screenshot 2021-03-18 at 16 25 47](https://user-images.githubusercontent.com/3938372/111625737-a38c6300-8806-11eb-8f54-cfb1cc555aac.png)

**Comment by edvardchen** [comment]
You can work around this with [ignoreProperty](https://github.com/edvardchen/eslint-plugin-i18next#ignoreproperty) option

**Comment by ivansky** [comment]
@edvardchen Is there possibility check Typename of the object and ignore it completely, e.g. `SxStyleProp`. There is no possibility to ignore everything that is classname string or custom style property.

**Comment by bignimbus** [comment]
I think it makes sense to allow developers to ignore all object keys.

Somewhat related: the ability to pass regular expressions to ignore lists would be helpful as well, for this case and others.

**Comment by edvardchen** [comment]
actually `ignoreProperty` accepts regex @bignimbus

**Comment by edvardchen** [comment]
> We upgraded to 6 version and the issue appears, is it intended behaviour?

version 6 of what? eslint? @ivansky

**Comment by ivansky** [comment]
@edvardchen Unfortunately, it doesn't help me to resolve the issue **explicitly**.
Would it be easier if I make PR with this change or do you have any concerns to ignore some sort of parent types or/and all object keys?

Sorry, regarding version I might take a version from another library mistakenly, probably it was the latest version, it means 5+.

**Comment by edvardchen** [comment]
I misunderstood your issue. Sure we should ignore         all property
names. There is a bug in my code. I have fixed it. I will release new
version tmr

Ivan Martianov ***@***.***>于2021年4月7日 周三20:07写道：

**Comment by edvardchen** [comment]
@ivansky maybe you can try the `ignore_object_property_name` branch. Help me check if it works

**Comment by ivansky** [comment]
@edvardchen I have tried your `ignore_object_property_name` branch and it does work for me. Well done!
Will wait for a next version ;)

**Comment by edvardchen** [comment]
try the v5.1.1
