### ISSUE TITLE
Ignore files

### ISSUE THREAD

**Issue by sshmyg** [edvardchen/eslint-plugin-i18next#64]
Hello
Is it possible to add ignore option for files? For  example to turn off validation for all `stories` files. (eg. file name `Counter.stories.tsx`)

Thanks

**Comment by edvardchen** [comment]
why not use [overrides](https://eslint.org/docs/user-guide/configuring/configuration-files#how-do-overrides-work)

**Comment by sshmyg** [comment]
> why not use [overrides](https://eslint.org/docs/user-guide/configuring/configuration-files#how-do-overrides-work)

Will try. Thanks
