### ISSUE TITLE
Typescript example not matching actual behavior 

### ISSUE THREAD

**Issue by AlexaLyu** [edvardchen/eslint-plugin-i18next#65]
Typescript example not matching actual behavior. In 5.1.2 string union will be detected as incorrect. It generates too much noise. 
![image](https://user-images.githubusercontent.com/1530659/144349903-70a68208-600c-4584-94da-804d6c5366be.png)

**Comment by nickbouton** [comment]
@edvardchen FYI it looks like this is fallout from the change made to TS support in #56. We're seeing a number of false positives in our TypeScript project based on what is supposed to be allowed based on the docs.

**Comment by nickbouton** [comment]
@edvardchen FYI it looks like this is fallout from the change made to TS support in #56. We're seeing a number of false positives in our TypeScript project based on what is supposed to be allowed per the docs.

**Comment by edvardchen** [comment]
the original implementation was flawed and it just happened to work by luck. A correct implementation requires a lot of efforts.  

You can downgrade to v5.1.1  as a temporary solution.

**Comment by edvardchen** [comment]
@nickbouton  try the prerelease version v6.0.0-1
