### ISSUE TITLE
Support -fix and add 'replace' option 

### ISSUE THREAD

**Issue by aburtsev** [edvardchen/eslint-plugin-i18next#66]
The idea is if we try to internationalize the existing app, we'll see a lot of errors, which at the first glance can be easily fixed automatically.
My suggestion is to add a property `replaceFnName` or something like this and make the rule fixable.

**Example:**
Option `replaceFnName` is equal to `i18nex.t`

JSX text:
```
//incorrect
<div foo="foo"></div>
<div foo={"foo"}></div>

```
after eslint -fix
```
<div foo={ i18nex.t('foo', 'foo') }></div>
<div foo={ i18nex.t('foo', 'foo') }></div>
```

@edvardchen what do think? I can create PR if you find this idea interesting

**Comment by edvardchen** [comment]
Emm, I think the fix might be a little risky since it requires i18next module. It's difficult to make a safe fix

**Comment by aburtsev** [comment]
To be clear I meant that i18next.t is just a variable, so you can use any function name you want. 
But anyway I think you are right. Any solution will contradict the best practices of eslint. Because in this case, we need also to add imports and in some cases initialization for the function. Otherwise fix will help a lot, but will produce broken code.
Thanks a lot for the answer and for the lib. It helped greatly to automate the internationalization of existence app
