### ISSUE TITLE
Support for curried functions

### ISSUE THREAD

**Issue by Tiberriver256** [edvardchen/eslint-plugin-i18next#69]
Example curried function from React MUI styled components

```
import { styled } from '@mui/system';

const MyComponent = styled('div')((theme) => ({
  color: 'darkslategray',
  backgroundColor: 'aliceblue',
  padding: 8,
  borderRadius: 4,
}));
```

Adding the eslint rule `ignoreCallee: ["styled"]` ignores the `div` string but does not ignore the `darkslategray`

**Comment by edvardchen** [comment]
@Tiberriver256 actually it does support. Try `ignoreCallee: ["styled.*"]`
