### ISSUE TITLE
missing lodash dependency

### ISSUE THREAD

**Issue by ivanrosvimi** [edvardchen/eslint-plugin-i18next#77]
I am trying to include your plugin in a project with `eslint` through the `pre-commit` tool, but as you use the `lodash` dependency in your code and it is not specified in your direct dependencies it fails me because I have to include it manually. 

I would like you to include this `lodash` dependency directly in your `package.json` instead of relying it from third party dependencies.

**Comment by edvardchen** [comment]
my bad. fixed in 6.0.0-4
