### ISSUE TITLE
Json schema does not allow passing regexp.

### ISSUE THREAD

**Issue by mathieutu** [edvardchen/eslint-plugin-i18next#83]
Hi, thanks for this plugin.

The code [allows passing](https://github.com/edvardchen/eslint-plugin-i18next/blob/15cf85b86c59639dd61ee0b9ec998830624d463f/lib/helper/generateFullMatchRegExp.js#L2) regexp in include or exclude (for example).

However, the rules options are validated against the json schema, and it [only allows](https://github.com/edvardchen/eslint-plugin-i18next/blob/15cf85b86c59639dd61ee0b9ec998830624d463f/lib/options/schema.json#L22) string.

Would you be open to a change?

Thanks.

**Comment by edvardchen** [comment]
Sure. Welcome to contribute
