### ISSUE TITLE
Does not identify html issues

### ISSUE THREAD

**Issue by syd-mitch** [edvardchen/eslint-plugin-i18next#89]
In my Angular 13 project I am running eslint-plugin-i18next 6.0.0-2. When I configure the mode to 'all' the untranslated strings in typescript files are successfully identified. However, it is unable to identify issues in html files.

**Comment by edvardchen** [comment]
Currently, the new version only supports React framework. I will consider supporting Angular when I have time. Cannot guarantee anything.

**Comment by armellarcier** [comment]
Do you have time ?
