### ISSUE TITLE
Can't ignore "&ndash;"

### ISSUE THREAD

**Issue by 3raser95** [edvardchen/eslint-plugin-i18next#93]
I've been trying to ignore the string \&ndash; but the rule doesn't seem to be working for it. I've used this rule:
`"i18next/no-literal-string": [
		2,
		{
			"words": {
				exclude: ["&ndash;", "Option"]
			}
		}
]`

With this rule the Option gets ignored fine inside a span element, but \&ndash; inside span doesn't get ignored. As far as I know the & and ; don't have a special meaning in regex so it should work as is. Is this a bug or am I doing something wrong?

**Comment by 3raser95** [comment]
Found out that I need to exclude "\u2013" even though in my files they are written like &ndash; which is quite confusing and I still think it should be fixed.

**Comment by edvardchen** [comment]
I understand your concern. It will be nice that we can ignore those unicode characters that are not in natural languages. But I don't know if there is a general way to recognize them. 

In new version `v6.0.0-7` the `exclude` option can accept regex as params now only if your eslint configuration is written in javascript. You can experiment with regex to see if it's possible. And welcome PR any time

**Comment by edvardchen** [comment]
It turned out that [Babel JSX compiler converts HTML entities into the unicode characters they represent](https://github.com/rescript-lang/rescript-react/issues/15)

I will fix it in https://github.com/edvardchen/eslint-plugin-i18next/pull/108
