### ISSUE TITLE
Whitespace around excluded words

### ISSUE THREAD

**Issue by 3raser95** [edvardchen/eslint-plugin-i18next#94]
I have indented jsx like this:
`return (`
`    <div className="alert alert-danger" role="alert">`
`        {t("No user details were found")}!`
`    </div>`
`)`

The plugin complains about the exclamation point. When I try to exclude it with "words": { exclude: ["!"] } the warning doesn't go away. If I remove the indentations in the jsx then the warning goes away. I had to add this to eslintrc: "words": { exclude: ["!\\s*"] } to ignore all whitespace after the exclamation point created by the indentation in order to get rid of the warning.

I think the plugin should ignore all whitespace at least created by indentation if not all whitespace.

**Comment by ElPrudi** [comment]
Same here. Characters like "!", "?" or "$" can not be excluded. Basically most characters that are part of the regex syntax.
Some of the characters can be excluded with "\\" before them. 

Also complex regexes also fail as the input is treated as characters for a regex.

**Comment by edvardchen** [comment]
Actually, it's not like that. It's a bug. The plugin should have ignored all special characters which match the patterns in the [default configuration ](https://github.com/edvardchen/eslint-plugin-i18next/blob/97604c7e6da8bc5ceb17b5fd40736bb6f620359e/lib/options/defaults.json#L21)
